baseURL = 'https://paweber86.github.io/trauer-begleitung/'
title = "Bärbel Frohnmeier"
languageCode = 'de'
defaultcontentlanguage = "en"

paginate = 20

#theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[services]
[services.disqus]
disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Bärbel Frohnmeier"
  info = "Trauer Begleitung"
  description = "Hier steht eine Beschreibung"
  keywords = "Hier stehen Schüsselwörter"
  #avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"
  since = 2024
  enableTwemoji = true
  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"